services:
  server:
    restart: always
    tty: "true"
    build:
      context: ./server
      dockerfile: Dockerfile
    # platform: linux/amd64
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
      - "2000-2020:2000-2020"
      - "2000-2020:2000-2020/udp"
    volumes:
      - ./server:/app/server
      - server_node_modules:/app/server/node_modules
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app/client
      - client_node_modules:/app/client/node_modules
volumes:
  server_node_modules:
  client_node_modules:
