services:
  server:
    restart: always
    tty: "true"
    build:
      context: ./server
      dockerfile: Dockerfile
    # platform: linux/amd64
    environment:
      - DOMAIN=http://host.docker.internal
      - CORS_ORIGIN_LIST=http://host.docker.internal:3002,https://192.168.35.25:3002
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
      # - "2000-2020:2000-2020/udp"
    volumes:
      - ./server:/app/server
      - server_node_modules:/app/server/node_modules
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    # environment:
    #   # - REACT_APP_SERVER_URL=http://host.docker.internal:5001
    #   - HOST=0.0.0.0
    #   - HTTPS=true
    #   - SSL_CRT_FILE=./.cert/cert.crt
    #   - SSL_KEY_FILE=./.cert/cert.key
    ports:
      - "3002:3002"
    volumes:
      - ./client:/app/client
      - client_node_modules:/app/client/node_modules
volumes:
  server_node_modules:
  client_node_modules:
